### ISSUE TITLE
CanTheyExpressMiddlewareUsageError not used

### ISSUE THREAD

**Issue by cwkingjr** [hlfshell/CanThey#2]
CanTheyExpressMiddlewareUsageError is declared in canTheyExpress but not thrown/referenced.

**Comment by hlfshell** [comment]
Good catch. It's a leftover from the original idea where the middleware would throw an error based on its usage. You can see its original prupose in the history of the file here:

https://github.com/hlfshell/CanThey/commit/e43b8d805450bece0b55395ccd0b1df69a1988f7

I will remove and republish without the error.

**Comment by hlfshell** [comment]
This has been resolved in the most recent push and published as 2.1.2 on npm
